In [ ]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

In [18]:
import numpy as np

In [102]:
def apply_vander(num_list,N=0,increasing=False):
    if N == 0:
        N = len(num_list)
    vander_list = []
    for i in range(N):
        colm_list = []
        for j in range(len(num_list)):
            colm_list.append(num_list[j]**(N-1-i))
        if increasing == True:
            vander_list.insert(0,colm_list)
        else:
            vander_list.append(colm_list)
    return vander_list

In [119]:
vander_list = apply_vander([1,2,3,4,5],5)
np.column_stack(vander_list)                                             # result 1 as vander numpy array

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [120]:
vander_list = apply_vander([1,2,3,4,5],increasing=True)
np.column_stack(vander_list)                                            # result 2 as vander numpy array

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [118]:
vander_list = apply_vander([1,2,3,4,5])
vander_matrix = np.matrix(vander_list)
vander_matrix.T                                                         # result 3 as vander matrix

matrix([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [256,  64,  16,   4,   1],
        [625, 125,  25,   5,   1]])